In [2]:
import numpy as np

In [4]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [8]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [10]:
np.multiply(a,a)

array([[ 1,  4],
       [ 9, 16]])

In [12]:
my_array = np.array([1,2,3])
my_array+5

array([6, 7, 8])

In [54]:
c = np.ones((3,3))
# c = np.zeros((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
#c + a
c + my_array

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

### آیا میتوان یک ماتریس (3و1) را با یک ماتریس (1و3) جمع کرد؟ حاصل چند در چند خواهد بود؟

In [38]:
s = np.random.uniform(1,10,(3,3))
s

array([[2.95964531, 2.45440228, 3.60867688],
       [5.89738699, 5.24820902, 2.92952345],
       [3.15978764, 8.29167406, 6.60769931]])

In [40]:
np.sum(s)

41.15700494325412

In [44]:
np.subtract(s,c)

array([[1.95964531, 1.45440228, 2.60867688],
       [4.89738699, 4.24820902, 1.92952345],
       [2.15978764, 7.29167406, 5.60769931]])

In [50]:
np.divide(s,2)
np.floor_divide(s,2)

array([[1., 1., 1.],
       [2., 2., 1.],
       [1., 4., 3.]])

In [56]:
np.arange(1,10,3)

array([1, 4, 7])

In [58]:
a_2 = a>2
a[a_2]

array([3, 4])

In [64]:
np.size(s)
np.shape(s)

(3, 3)

In [66]:
np.unique(c)

array([1.])

In [76]:
np.union1d(s,c)
np.intersect1d(s,c)

array([], dtype=float64)

In [82]:
np.mean(s)
np.std(s)
np.var(s)

3.655324354933364

## pandas

In [97]:
import pandas as pd

mydict = {'col1':[1,2,3,4],'col2':[4,5,6,7],'col3':[7,8,9,2],'col4':[1,5,9,5]}
df = pd.DataFrame(mydict,index = ['row1','row2','row3','row4'], columns =['col1','col2','col3','col4'])
df

col1  col2  col3  col4
row1     1     4     7     1
row2     2     5     8     5
row3     3     6     9     9
row4     4     7     2     5

In [99]:
df.index

Index(['row1', 'row2', 'row3', 'row4'], dtype='object')

In [101]:
df.columns

Index(['col1', 'col2', 'col3', 'col4'], dtype='object')

In [103]:
df.values

array([[1, 4, 7, 1],
       [2, 5, 8, 5],
       [3, 6, 9, 9],
       [4, 7, 2, 5]], dtype=int64)

In [107]:
df.iloc[1][3]

C:\Users\Hamed\AppData\Local\Temp\ipykernel_12868\1959163346.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[1][3]


5

### در مورد متد پایین و تفاوت انها تحقیق کنید
### loc

In [115]:
df["col5"] = [11,22,44,55]
df

col1  col2  col3  col4  col5
row1     1     4     7     1    11
row2     2     5     8     5    22
row3     3     6     9     9    44
row4     4     7     2     5    55

In [123]:
df.reset_index(drop = True , inplace = True)
df

col1  col2  col3  col4  col5
0     1     4     7     1    11
1     2     5     8     5    22
2     3     6     9     9    44
3     4     7     2     5    55

In [133]:
df.drop('col1', axis=1, inplace = True)
df

col2  col3  col4
1     5     8     5
2     6     9     9
3     7     2     5

In [137]:
df.replace(9,10,inplace = True)
df

col2  col3  col4
1     5     8     5
2     6    10    10
3     7     2     5

### چگونه نام یک ستون را تغییر دهیم؟

In [149]:
df.sort_values(by='col2',ascending = False)

col2  col3  col4
3     7     2     5
2     6    10    10
1     5     8     5

## what is the sort_index?

In [152]:
df.head()

col2  col3  col4
1     5     8     5
2     6    10    10
3     7     2     5

In [154]:
df.tail()

col2  col3  col4
1     5     8     5
2     6    10    10
3     7     2     5

### NumPy

    یک آرایه NumPy از اعداد 1 تا 10 ایجاد کنید.
    میانگین و انحراف معیار این آرایه را محاسبه کنید.
    یک آرایه 3x3 از اعداد تصادفی ایجاد کنید.
    عناصر قطر اصلی این آرایه را چاپ کنید.
    این آرایه را به یک آرایه 1 بعدی تبدیل کنید.

In [ ]:
### Pandas

     DataFrame  یک  با 10 سطر و 3 س ایجاد کنید.
    5 سطر اول و 5 سطر آخر DataFrame را نمایش دهید.
    اطلاعات آماری DataFrame را با استفاده از تابع describe() نمایش دهید.
    DataFrame را بر اساس یک ستون خاص مرتب کنید.
    یک ستون جدید به DataFrame اضافه کنید که شامل مجموع دو ستون دیگر باشد.